// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhqidrvekucovccbnyjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ocWlkcnZla3Vjb3ZjY2JueWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTUyMzcsImV4cCI6MjA2MjYzMTIzN30.Da-RxY-JyUy1t5m2DBsZtscoeH_TDKq637UfEdf_ogc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);